name: Build and Test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies api-service
        run: pnpm install
        working-directory: ./services/api-service

      - name: Install dependencies redirect-service
        run: pnpm install
        working-directory: ./services/redirect-service

      - name: Build api-service
        run: pnpm tsc
        working-directory: ./services/api-service

      - name: Build redirect-service
        run: pnpm tsc
        working-directory: ./services/redirect-service

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push api-service image
        uses: docker/build-push-action@v5
        with:
          context: ./services/api-service
          push: true
          tags: rahulch49/url-shortner-api-service:latest

      - name: Build and push redirect-service image
        uses: docker/build-push-action@v5
        with:
          context: ./services/redirect-service
          push: true
          tags: rahulch49/url-shortner-redirect-service:latest

