name: Build and Test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies api-service
        run: pnpm install
        working-directory: ./services/api-service

      - name: Install dependencies redirect-service
        run: pnpm install
        working-directory: ./services/redirect-service

      - name: Build api-service
        run: pnpm tsc
        working-directory: ./services/api-service

      - name: Build redirect-service
        run: pnpm tsc
        working-directory: ./services/redirect-service

